# Title: Predicting New Advertiser Spend
#search advertising, budgeting, revenue forecasts, time series, web logs, data science {-}
#### Keywords {-}


Predict how much an advertiser is capable of spending before they begin spending

## A beginning: How much of this advertiser's budget are we getting and how much of it could we be getting 

Microsoft has a goal to grow its Bing advertising product from a $7 billion dollar per year business to a $10 billion dollar per year business. There are two major strategies it can leverage to achieve this goal: increase its Bing user base and syndicate partnerships to increase aggregate network supply and or increase its advertisers' current share of wallet - the amount of an advertiser's budget allocated toward Bing versus other publishers. As the search engine experience between Google and Bing has become undifferentiated, growing user base is a long term challenge. More immediate impact can be realized by focusing on capturing a greater share of advertisers’ wallet. To best direct sales teams in this effort, Microsoft needs to understand how much of an advertiser's budget they could be getting relative to what they're currently getting. Drawing this distinction falls into the scope of Microsoft’s Search Data Science team.


## A middle: Signals for scalability

Growing advertiser budgets with Bing’s current market share is at its core a big data problem. Initially, we need to understand three key elements: percent of targeted supply advertiser is capturing (search share), cost to advertiser of capturing incremental supply, and the advertiser’s capabilities to scale budget. Knowledge of the network supply and demand gap help sales understand maximum potential. However, understanding advertiser scalability allows sales teams to focus efforts on those advertisers that are most able to increase budgets. In other words, insight into advertiser scalability provides sales teams actual (as opposed to maximum) advertiser potential. Determining actual potential requires a prediction of how much an advertiser could spend. In order to make this prediction, Microsoft needs to build an analytics solution for forecasting the future values of multiple time series.[@ZoteroStart] Several data points will be crucial to this solution: Internet Explorer/Edge Bing traffic log files for any given domain, web traffic stats from major search networks (which can be provided by 3rd parties) and a domain business vertical-classification algorithm. These data points will serve as core signals in the model. First, the vertical classification algorithm will group the new advertiser with other like-advertisers. Web log data from the vertical cohort provides directional data on the amount of search demand for any given vertical. And traffic data from other publishers, like Google, help identify major variances in expected vs actual traffic.


## An end: Predictive analytics as a sales motion
By developing a model for how much an advertiser can actually spend, Microsoft can establish a benchmark for each advertiser and alert sales teams to how a particular advertiser is trending against its benchmark (share of wallet opportunity). Sales teams, in turn, can focus on those advertisers with the biggest upside - high spenders and high trailers. Better alignment between sales teams and actual advertiser potential can help optimize Bing’s sales motion and drive revenue growth at a faster rate. While this model can help Microsoft toward its $10 billion target, the possible downside is that sales neglects advertisers without share-of-wallet opportunity, creating a crowding-out effect. To counter this, sales teams should be held accountable for both total accounts and revenue in their book of business.


