# Using Machine Vision to Predict Wave Quality {#Surf's Up}

#### Keywords {-}

surf forecast, video analysis, computer vision, machine learning, wave quality, OpenCV, parallax

## Dawn Patrol Blues

For those who work 9-5, catching surf usually means waking up at dawn. To sleep or not to sleep becomes the routine question. To help answer that surfers can consult several websites that offer daily forecasts and wave condition rankings. Some like the leading surf content site,[surfline](http://www.surfline.com/home/index.cfm), even offer live video streams like. Yet surfers are all too familiar with the scenario of a good forecast going bad or of judgements based on live video proving poor. Known as the dawn patrol blues - these scenarious leave the early risers at the beach with no surfable waves in sight. But advancements in computer vision and machine learning offer new hope to avoid these situations. Through the analysis of real-time surf cameras, we can improve the current forecast methodology and perhaps develop an eye for good surf that out performs our own.



## Computer Vision Goes Surfing

How waves are created and how they are different depend on wind, fetch, swell period, and the ocean floor (bathymetry) [@misc]. Each of these variables, themselves, can fluctuate quite a bit, making accurate predictions of wave quality for most surf spots challenging. Current datasets used to gather these variables include information from: the National Data Buoy Center, NOAA (nationa oceanic and atmosphere administration) for tide information and offshore storms, General Bathymetric Chart of the Oceans, and localized weather conditions from Weather Underground. All of these variables are currently modeled into a forecast of 5 categorical wave conditions across major surf forecast sites: poor, fair, poor to fair, fair to good, good. What is actually used to define these categories is based on two factors: 
1. Scientific knowledge of how swell interacts with bathymetry and local weather conditions
2. User feedback. 
User feedback is highly subjective and the current science behind wave prediction leaves wide confidence intervals. Wave speed, wave height, and predicted time-on-wave are metrics that are directly observable via real-time cameras and all offer a more confident, objective assessment of surf quality. Setting a pipeline between camera feeds from [Surfline](http://www.surfline.com/home/index.cfm) and a computer vision framework provides the analytics platform needed to run prediction models on the above mentioned metrics. OpenCV[@misc] could offer the framework needed for video analysis and machine learning will provide the prediction models for the said 3 metrics.

Obtaining these metrics pose challenges including: no light during pre-dawn periods, low light from marine layer obstruction, identification of starting and stopping points within the video to calculate wave speed, reference points to calculate wave height, and surfing surfers to calculate time-on-wave. To overcome the latter three, a known point of reference needs to be established for each surf spot. This might require manual labor. However, some surf spots already offer known references such as life guard towers which have standard heights or man made landmarks like car railings. Other required measurements may require social crowd sourcing. Once an absolute reference point is known, parallax can be used to measure distances which, in turn, will be used to quantify rates. For instance, a computer can be trained to identify the lip of the wave from the face and measure the angle between where the lip started and where it ended relative to the known point to compute the distance traveled. The camera's time stamp would then be applied to the distance to determine the rate or speed-of-wave.

Adding in wave speed, wave height, and predicted time-on-wave from the model could eventually be used to train the independent variables modeled into surf forecasting and help fine-tune those models. The result should be forecasts with better confidence intervals and a less biased status of wave conditions.


## Surf Those Blues Away

Most important, surfers are provided real-time information that is more useful in making a decision on whether or not to surf at a particular spot. By feeding the prediction models back into a website like surfline where viewers can watch waves in real-time, those same viewers will also be able to get a sense of how fast the wave is moving and how long they can expect to be surfing on a wave: criteria that is not easily measured by the human eye. These insights could also be leveraged by organizations like the World Surf League who are responsible for determining ideal surf conditions for competitions or the Olympics Committe (surfing will be in the next Olympics) which needs a more objective way of measuring wave difficulty for scoring. The additional insight around local conditions will, at the very least, help surfers avoid those dawn patrol blues.